// Generated by CoffeeScript 1.6.1
(function() {
  var Application;

  Application = (function() {

    function Application() {
      this._database = new Database(LocalStorageBackend, {
        context: 'synclist'
      });
      this._manager = new Manager(this._database);
      this._userInterface = new UserInterface(this._manager);
    }

    return Application;

  })();

  (typeof exports !== "undefined" && exports !== null ? exports : this).Application = Application;

  jQuery(function() {
    return window.ApplicationInstance = new Application();
  });

}).call(this);
